### ISSUE TITLE
Why is `lib` prefix removed from library name?

### ISSUE THREAD

**Issue by mehaase** [novocaine/rust-python-ext#4]
After building a rust library, the `lib` prefix is removed, e.g. `libfoo.so` is renamed to `foo.so`. Why is this being done? I had a hard time working around this on a project I'm working on. Eventually, I resorted to naming my library such that the output file is `liblibfoo.so`.

Here is my [setup.py](https://github.com/TeamHG-Memex/rs-bkstring/blob/a843e73ece87056fbaa2352636287d355b497354/python/setup.py) and my [Cargo.toml](https://github.com/TeamHG-Memex/rs-bkstring/blob/a843e73ece87056fbaa2352636287d355b497354/Cargo.toml).

I'm probably missing something obvious... would appreciate any feedback you can provide.

**Comment by novocaine** [comment]
Hey,

Well, if we didn't trim the 'lib' prefix you would need to do `import libfoo`. I have rarely seen a python extension that looked like that, so I think most people will want it trimmed. Python extensions often begin with _, but rarely lib (libxml comes to mind, maybe your naming situation is similar?).

I would welcome a pull request that added an option to explicitly name the output rather than the guessing game it currently plays.

https://github.com/novocaine/rust-python-ext/blob/master/rust_ext/__init__.py#L94

**Comment by mehaase** [comment]
Ahh, I had confused myself somewhere else in the process. Now I realize that this convention makes perfect sense. Please feel free to delete this issue :)

**Comment by Elfoniok** [comment]
Hey maybe i am not getting something but we don't use this like that.

If you want to pass some data between python and rust you still need some C glue code. Like Cffi for example right?

So we generate librustsomething.so with rust code, so we can use it to build actually cfffi library which will be imported as python module. 

After all rust-python-ext simply enable setuptools to intergrate building rust during install right?

**Comment by novocaine** [comment]
Okay totally fair for that use case. 

I dont want to break anyone - can we make it an opt-in thing please?

**Comment by novocaine** [comment]
(eg ability to specify the name directly as mentioned above)

**Comment by novocaine** [comment]
I have added an ext_name param to build_rust_cmdclass - I'm not sure if that helps you.

**Comment by Elfoniok** [comment]
Ok, i think its enough.
