### ISSUE TITLE
some help getting up and running with python3?

### ISSUE THREAD

**Issue by waynenilsen** [novocaine/rust-python-ext#6]
I have spent some time trying to get this working with python3 and I'm relatively close but I do need some help. I think this maybe should go as a bug report to `rust-cpython` but i wanted to check here first. `build_rust` works but then when I go to import i get 

```
ImportError: dynamic module does not define module export function (PyInit__python_boilerplate)
```

I did some searching around and it looks like the function should be defined with the build options that were given eg it did call `cargo build --manifest-path extensions/Cargo.toml --release --features python3-sys` and looking through the macro definitions in `rust-cpython` it seems that for some reason the conditional compilation stuff isn't happening correctly and the config parameter is not being set to python3 all the way through

**Comment by waynenilsen** [comment]
also if you could help me debug this that would be great 

https://travis-ci.org/waynenilsen/cookiecutter-python-rust-proto/builds/188072799

**Comment by waynenilsen** [comment]
I'm trying to make a [cookiecutter](https://github.com/audreyr/cookiecutter) project template for python rust extensions that works with travis and when we get windows running appveyor. I am getting started by making a prototype that is running the travis builds to ensure correctness. I had python 2 working then tried to change my cookiecutter template and it went back to not working (on ci) works on local. Can't seem to figure out the difference

**Comment by naufraghi** [comment]
I set up a GitLab mirror of this repo with CI enabled, that has some test running: https://gitlab.com/naufraghi/rust-python-ext

The machine setup is in the `Dockerfile`, the Rust part in the `.gitlab-ci.yml`, the Python part in the `tox.ini` file.

The custom docker image is not a requirement, but is faster.

**Comment by novocaine** [comment]
As I think you might have worked out, that first error may suggest that rust-cpython has made a python 2 library instead of a python 3 one. 

The naming convention for module init function changed from python 2 to python 3 and your python 3 interpreter can't find the python 3 one.

http://python3porting.com/cextensions.html

> The definition of the module initialization function has also changed. In Python 2 you declared a function to initialize the module like this:
> 
> PyMODINIT_FUNC init<yourmodulename>(void)
> In Python 3 this has changed to:
> 
> PyMODINIT_FUNC PyInit_<yourmodulename>(void)

To verify if this is the problem, you can dump the symbols your library does export; nm should do this on mac os x or linux.

I don't actively use this extension, but I merged https://github.com/novocaine/rust-python-ext/pull/5/commits/ec6a3c143d4ac0592f2f7358eb3d287ba45f59ba recently which altered how python3 is flagged to rust-cpython. Previously, we simply ensured that the correct python was in the PATH, which was enough for rust-cpython to pick up our intent, but this new merge signals python3 using --features which might be wrong / not working for you?

edit: actually, I suspect this removal of the PATH causes other problems anyway, like potential for a different interpreter to be targeted from the running script - that is the same major version but has an incompatible ABI, as is pretty common on python2. I should probably have looked at the change more carefully. 

Can you try restoring the env["PATH"] entry from the older version and see if that fixes your problem? Then we can maybe put together a PR.

**Comment by naufraghi** [comment]
I tested the extension only inside a virtualenv, in that case the `PATH` has as expected the local python binary at the first place. Other cases cannot be supported in fact...

I can understand that having no other way to tell `rust-cpython` the current executable, the `PATH` is a good workaround, I'll submit a partial revert of my PR.

I still don't understand way calling `python setup.py` using the current `PATH` later on `rust-cpython` ends up finding a different version.

**Comment by novocaine** [comment]
Thanks!

I was actually directing my comment at @waynenilsen but really appreciate you doing the PR :) lets see if it fixes his issue or not.

edit: I initially guessed that subprocess doesn't inherit the environment by default but I see it does ..

> If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment.

still, one breaking case would be when you use a python that isn't on the PATH to run setup.py

**Comment by naufraghi** [comment]
You are welcome, it was my fault :)

**Comment by ghost** [comment]
@waynenilsen I think I may have found something that you're grappling with, too: #16 - If you don't include the correct feature-hooks, rust-ext probably ends up failing to pass the directives to `cargo`, and the default for `cpython` is to build for Python 2, for some reason.

Essentially, `rust-ext` uses two "hook" features that you must define in your Cargo manifest, which delegate to the `cpython` features to pick the right version according to which Python interpreter runs `setup.py`. You need to define those. The `example` project for `rust-ext` has these hooks defined. Don't forget to add `default-features = false` to your `[dependencies.cpython]` block, also.
